spring:
  application:
    name: gym-crm

  # Db Settings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gym_local
    username: postgres
    password: 1
    
  # JPA And Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: gym_local

  # SQL Script Settings
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-local.sql
      defer-datasource-initialization: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

