spring:
  application:
    name: gym-crm
  # Db Settings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gym
    username: postgres
    password: 1
    
  # JPA And Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: gym

  # SQL Script Settings
  sql:
    init:
      mode: always
      platform: postgresql
      defer-datasource-initialization: false
  cloud:
    discovery:
      enabled: true
    # Resilience4j Circuit Breaker configuration
    circuitbreaker:
      resilience4j:
        circuit-breakers:
          trainerHoursService:
            register-health-indicator: true
            failure-rate-threshold: 50
            sliding-window-size: 10
            minimum-number-of-calls: 6
            permitted-number-of-calls-in-half-open-state: 5
            wait-duration-in-open-state: 30s
            automatic-transition-from-open-to-half-open-enabled: true
            record-exception:
            - org.springframework.web.client.ResourceAccessException
            - java.io.IOException
            - org.springframework.web.client.HttpServerErrorException 
            - io.github.resilience4j.feign.FeignException
  feign:
    circuitbreaker:
      enabled: true

  config:
    import:
    - "optional:configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
      
app:
  # --- JWT Settings (JwtConfig) ---
  jwt:
    secret: hd72J#8!pzR@X5vmA6qTL*19ePfKzLbWuYxBVcN34
    expiration-ms: 7200000
    blacklist-retention-hours: 2

  # --- LoginSecurityConfig Settings (LoginSecurityConfig) ---
  security:
    login:
      max-attempts: 3
      lockout-duration-minutes: 5
# ----------------------------------------------------

# Logs
logging:
  level:
    root: WARN
    com.epam.gym_crm: INFO
    org.springframework: WARN
    org.hibernate: WARN

# Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus" 
  endpoint:
    health:
      show-details: "always"